CREATE TABLE DEPT (
    ID NUMBER(7) NOT NULL,
    NAME VARCHAR(25)
);

DESC DEPT;

INSERT INTO DEPT (ID, NAME)
SELECT DEPARTMENT_ID, DEPARTMENT_NAME
FROM DEPARTMENTS;

SELECT * FROM DEPT;

CREATE TABLE EMP (
    ID NUMBER(7),
    LAST_NAME VARCHAR(25),
    FIRST_NAME VARCHAR(25),
    DEPT_ID NUMBER(7)
);

DESC EMP;

CREATE TABLE EMPLOYEES2 AS
SELECT 
    EMPLOYEE_ID AS ID,
    FIRST_NAME,
    LAST_NAME,
    SALARY,
    DEPARTMENT_ID AS DEPT_ID
FROM EMPLOYEES;

DESC EMPLOYEES2;

ALTER TABLE EMPLOYEES2 READ ONLY;

ALTER TABLE EMPLOYEES2 READ WRITE;

INSERT INTO EMPLOYEES2 (ID, FIRST_NAME, LAST_NAME, SALARY, DEPT_ID)
VALUES (34, 'GRANT', 'MARCIE', 5678, 10);

SELECT * FROM EMPLOYEES2;

DROP TABLE EMPLOYEES2;

ALTER TABLE EMP
ADD CONSTRAINT MY_EMP_ID_PK PRIMARY KEY (ID);

DESC EMP;

DROP TABLE DEPT;

DROP TABLE EMP;