CREATE VIEW EMPLOYEES_VU AS
SELECT 
    EMPLOYEE_ID,
    FIRST_NAME || ' ' || LAST_NAME AS EMPLOYEES,
    DEPARTMENT_ID
FROM EMPLOYEES;

SELECT * FROM EMPLOYEES_VU;

SELECT EMPLOYEES, DEPARTMENT_ID
FROM EMPLOYEES_VU;


CREATE VIEW DEPT50 AS
SELECT 
    EMPLOYEE_ID AS EMPNO,
    LAST_NAME AS EMPLOYEE,
    DEPARTMENT_ID AS DEPTNO
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 50;

SELECT * FROM DEPT50;

UPDATE DEPT50
SET DEPTNO = 80
WHERE EMPLOYEE = 'Matos';


CREATE SEQUENCE DEPT_ID_SEQ
START WITH 200
INCREMENT BY 10
MAXVALUE 1000;

SELECT DEPT_ID_SEQ.NEXTVAL FROM DUAL;
SELECT DEPT_ID_SEQ.CURRVAL FROM DUAL;


INSERT ALL
    INTO DEPT (ID, NAME)
    VALUES (DEPT_ID_SEQ.NEXTVAL, 'EDUCATION')
    INTO DEPT (ID, NAME)
    VALUES (DEPT_ID_SEQ.NEXTVAL, 'ADMINISTRATION')
SELECT * FROM DUAL;


CREATE INDEX DEPT_NAME_IDX ON DEPT(NAME);


CREATE SYNONYM EMP_SYN FOR EMPLOYEES;